# menu links via config file
main:
- name: Github
  url: http://www.github.com/
  weight: 90
  params:
    blank: true
- name: Google
  url: http://www.google.com/
  weight: 100
  params:
    blank: true